### ISSUE TITLE
GPU for ns-train splatfacto

### ISSUE THREAD

**Issue by AlexGorshunov** [escontra/gauss_gym#11]
Hello

What GPU did you use for step:
With the ns conda environment active, train a gaussian splat with bash scene_generation/iphone/polycam_scenes.sh <POLYCAM_PATH>

I have tried two types of GPU: 4090 and L40. In both cases I got an error after 20% of training:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.63 GiB. GPU 0 has a total capacty of 44.31 GiB of which 4.63 GiB is free. Including non-PyTorch memory, this process has 39.67 GiB memory in use. Of the allocated memory 35.84 GiB is allocated by PyTorch, and 3.27 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by escontra** [comment]
For gaussian splat training both 4090 an L40 should definitely work. My guess is that OOM errors are caused by the `gsplat` `mcmc` splitting strategy, which lets the number of gaussians grow unbounded. Could you try disabling [this line](https://github.com/escontra/gauss_gym/blob/e3bb869807bf792a12f092381ab8ab8306aeef16/scene_generation/iphone/polycam_scenes.sh#L22) in `polycam_scenes.sh`. This should put a hard cap on the number of gaussians created.

**Comment by AlexGorshunov** [comment]
> For gaussian splat training both 4090 an L40 should definitely work. My guess is that OOM errors are caused by the `gsplat` `mcmc` splitting strategy, which lets the number of gaussians grow unbounded. Could you try disabling [this line](https://github.com/escontra/gauss_gym/blob/e3bb869807bf792a12f092381ab8ab8306aeef16/scene_generation/iphone/polycam_scenes.sh#L22) in `polycam_scenes.sh`. This should put a hard cap on the number of gaussians created.

Hello, It works for me. I have done this step with 30k iterations after disabling _gsplat mcmc_

Thnks, I am gonna do the next step.
